name: Main pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  main:
    runs-on: ubuntu-20.04
    env:
        CI_PUBLISH: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip-publish') }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Install dependencies
        run: echo "Install dependencies done"
      - 
        name: Check style
        run: echo "Check style done"
      - 
        name: Build      
        run: echo "Build done"
      - 
        name: Test
        run: echo "Test done"
      - 
        name: Bump verison
        id: bump_version
        if: ${{ env.CI_PUBLISH == true }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      -
        name: Set up QEMU
        if: ${{ env.CI_PUBLISH == true }}
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        if: ${{ env.CI_PUBLISH == true }}
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        if: ${{ env.CI_PUBLISH == true }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      -
        name: Build and push to DockerHub
        if: ${{ env.CI_PUBLISH == true }}
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: bauerbrun0/gh-test:${{ steps.bump_version.outputs.new_tag }},bauerbrun0/gh-test:latest